"""Validation/replay layer for the dynamic-exit redesign — run BEFORE
ever setting POLYMARKET_DYNAMIC_EXIT_ENABLED=true for real.

Unlike test_polymarket_exit_manager.py (which tests evaluate_dynamic_exit's
cascade logic against directly-constructed BtcMarketAssessment objects,
and record_exit_fill/reconcile_exit_fill in isolation), every test here
drives the REAL pipeline end to end:

    realistic BTC quote ticks
      -> BtcPriceHistoryStore.record_quote() (btc_market_data.py)
      -> BtcPriceHistoryStore.get_bars() (real OHLC aggregation)
      -> build_btc_momentum_evidence() / assess_btc_market() (btc_intelligence.py)
      -> evaluate_dynamic_exit() / check_and_execute_dynamic_exits() (exit_manager.py)

Tick sequences are generated by a SEEDED random walk (drift + noise) —
deterministic (same seed -> byte-identical ticks -> byte-identical
bars -> byte-identical assessment, every run) while still exercising
realistic, noisy, multi-tick-per-bar price action rather than a single
hand-picked number per bar. Each sequence's exact (drift, noise, seed)
parameters were found by search and are pinned here with the resulting
MomentumState recorded in a comment — if evidence.py's scoring ever
changes, these tests will fail loudly rather than silently drift.

POLYMARKET_DYNAMIC_EXIT_ENABLED and POLYMARKET_LIVE_AUTO_EXECUTE are
NEVER set to true in this repo's committed defaults — only inside
individual tests here, in-process, to exercise the code path; no test
in this file places a real order (PaperPolymarketGateway/a fake
order_placer only).
"""

from __future__ import annotations

import math
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from src.execution.emergency_stop import EmergencyStopStore
from src.market.indicators import vwap
from src.polymarket.btc_intelligence import assess_btc_market
from src.polymarket.btc_market_data import BtcPriceHistoryStore
from src.polymarket.client import NoActiveMarketError
from src.polymarket.engine import MarketHistory, run_cycle, settle_resolved_positions
from src.polymarket.exit_manager import (
    check_and_execute_dynamic_exits,
    evaluate_dynamic_exit,
    reconcile_exit_fill,
    submit_dynamic_exit,
)
from src.polymarket.gateway import LivePolymarketGateway, PaperPolymarketGateway
from src.polymarket.logger import PolymarketDecisionLogger
from src.polymarket.models import BinaryMarket, BookLevel, FillResult, OrderBookSnapshot, SubmissionOutcome
from src.polymarket.pending import PolymarketPendingOrderStore
from src.polymarket.positions import OpenPosition, PolymarketPositionStore
from src.polymarket.risk import PolymarketRiskManager
from src.polymarket.settings import PolymarketSettings
from src.polymarket.state import DailyPnlStateStore
from src.polymarket.strategy import BtcMomentumStrategy
from src.strategy.evidence import MomentumState

_VALID_KEY = "0x" + "a" * 64
_BASE_T = datetime(2026, 10, 8, 12, 0, 0, tzinfo=timezone.utc)
_AVG_FILL_PRICE = 0.36  # the real 2230z position this feature was built for
_TARGET_PRICE = round(_AVG_FILL_PRICE * 1.20, 4)  # 0.432


# --- Deterministic, realistic BTC tick generation -----------------------------

def _ticks_from_minute_closes(
    minute_closes: list[float], *, ticks_per_minute: int = 4, jitter: float = 0.02, seed: int,
) -> tuple[list[tuple[float, datetime]], datetime]:
    """Realistic multi-tick-per-minute price action: each minute's
    intended close gets `ticks_per_minute` samples, each jittered by a
    seeded PRNG -- same seed always produces the exact same ticks."""
    rng = random.Random(seed)
    ticks: list[tuple[float, datetime]] = []
    t = _BASE_T
    for close in minute_closes:
        for _ in range(ticks_per_minute):
            ticks.append((close + rng.uniform(-jitter, jitter), t))
            t += timedelta(seconds=60 // ticks_per_minute)
    return ticks, t


def _drifting_noisy_closes(*, drift: float, noise: float, seed: int, n: int = 45) -> list[float]:
    """A seeded random walk: closes[i] = closes[i-1] + drift + U(-noise,
    noise). Used to reach STABLE/WEAKENING/REVERSING deterministically
    -- see the per-state comments below for the exact search result."""
    r = random.Random(seed)
    closes = [100.0]
    for _ in range(1, n):
        closes.append(closes[-1] + drift + r.uniform(-noise, noise))
    return closes


def _strengthening_closes(n: int = 45) -> list[float]:
    """A mild, healthy uptrend with real pullbacks -- NOT a straight
    line (which reads as overbought/exhausted, see
    test_polymarket_btc_intelligence.py's own note on this). Verified:
    STRENGTHENING, weakening=0, strengthening=2
    ('trend_intact', 'rsi_healthy_range')."""
    return [100.0 + i * 0.05 + 1.0 * math.sin(i / 2.0) for i in range(n)]


# Pinned (drift, noise, seed) search results -- see this file's module
# docstring. All at n=45 bars (well above the 35-bar min_bars_for_indicators
# default), thesis_direction="bullish" (a YES/BTC-up position).
_STABLE_CLOSES = _drifting_noisy_closes(drift=-0.013308557506160237, noise=0.1303950481189401, seed=795667)
_STABLE_SEED = 795667  # verified: STABLE, weakening=2 strengthening=0 ('trend_flip',)

_WEAKENING_CLOSES = _drifting_noisy_closes(drift=-0.008470348278830142, noise=0.07175423306632496, seed=927143)
_WEAKENING_SEED = 927143  # verified: WEAKENING, weakening=4 ('trend_flip','structure_turning','macd_momentum_fading') -- 3 signals, >=2

_REVERSING_CLOSES = _drifting_noisy_closes(drift=-0.009602192505633364, noise=0.04001508891498909, seed=187487)
_REVERSING_SEED = 187487  # verified: REVERSING, weakening=5 ('trend_flip','reversal_signal') -- exactly 2 signals


def _feed(store: BtcPriceHistoryStore, minute_closes: list[float], *, seed: int) -> datetime:
    ticks, end_t = _ticks_from_minute_closes(minute_closes, seed=seed)
    for price, at in ticks:
        store.record_quote(price, at=at)
    return end_t


# --- Fakes / harness -----------------------------------------------------------

class _FakeClient:
    def __init__(self):
        self._books: dict[str, OrderBookSnapshot] = {}
        self._fills: dict[str, FillResult] = {}
        self._resolution: str | None = None
        self._place_outcome: SubmissionOutcome | None = None
        self.place_order_calls: list = []

    def set_order_book(self, token_id: str, book: OrderBookSnapshot) -> None:
        self._books[token_id] = book

    def set_fill_result(self, exchange_order_id: str, fill: FillResult) -> None:
        self._fills[exchange_order_id] = fill

    def set_resolution(self, outcome: str | None) -> None:
        self._resolution = outcome

    def set_place_outcome(self, outcome: SubmissionOutcome) -> None:
        self._place_outcome = outcome

    def get_order_book(self, token_id: str) -> OrderBookSnapshot:
        return self._books[token_id]

    def get_fill_status(self, exchange_order_id: str) -> FillResult:
        return self._fills[exchange_order_id]

    def get_resolution(self, condition_id: str) -> str | None:
        return self._resolution

    def place_order(self, order):
        self.place_order_calls.append(order)
        return self._place_outcome

    def find_active_btc_market(self, *, now=None):
        """These replay tests never exercise entry logic -- a clean
        "no market" skip, same convention as test_polymarket_engine.py's
        own fake when market=None."""
        raise NoActiveMarketError("no market open right now -- not used by these replay tests")


def _book(bid: float, *, size: float = 100.0) -> OrderBookSnapshot:
    return OrderBookSnapshot(
        token_id="tok-1", bids=(BookLevel(price=bid, size=size),), asks=(BookLevel(price=bid + 0.02, size=size),),
        fetched_at=datetime.now(timezone.utc),
    )


def _position(**overrides) -> OpenPosition:
    now = datetime.now(timezone.utc)
    defaults = dict(
        condition_id="cpc-btc-updown-15m-2026-10-07-2230z", token_id="tok-1", outcome="YES",
        requested_size_usd=5.0, filled_shares=5.0, avg_fill_price=_AVG_FILL_PRICE, order_id="CZ510YB5PYWT",
        client_order_id="client-2230z", status="filled", opened_at=now, close_time=now + timedelta(minutes=10),
    )
    defaults.update(overrides)
    return OpenPosition(**defaults)


def _settings(**overrides) -> PolymarketSettings:
    return PolymarketSettings.from_env(env=dict(overrides))


def _logger(tmp_path: Path) -> PolymarketDecisionLogger:
    return PolymarketDecisionLogger(tmp_path / "decisions.jsonl", also_console=False)


def _paper_harness(tmp_path: Path):
    settings = _settings(POLYMARKET_DYNAMIC_EXIT_ENABLED="true")
    assert settings.dynamic_exit_enabled is True  # explicit in-test override only -- never a committed default
    client = _FakeClient()
    decision_logger = _logger(tmp_path)
    gateway = PaperPolymarketGateway(settings, decision_logger)
    pending_store = PolymarketPendingOrderStore(tmp_path / "pending.json")
    position_store = PolymarketPositionStore(tmp_path / "positions.json")
    state_store = DailyPnlStateStore(tmp_path / "pnl.json")
    btc_price_store = BtcPriceHistoryStore(tmp_path / "btc.json")
    return dict(
        client=client, settings=settings, gateway=gateway, position_store=position_store,
        pending_store=pending_store, state_store=state_store, decision_logger=decision_logger,
        btc_price_store=btc_price_store,
    )


def _live_harness(tmp_path: Path, *, auto_exit_enabled: bool = True):
    settings = _settings(
        POLYMARKET_TRADING_MODE="live", POLYMARKET_PRIVATE_KEY=_VALID_KEY,
        POLYMARKET_LIVE_TRADING_CONFIRMED="true",
        POLYMARKET_AUTO_EXIT_ENABLED="true" if auto_exit_enabled else "false",
        POLYMARKET_DYNAMIC_EXIT_ENABLED="true",
    )
    assert settings.dynamic_exit_enabled is True  # explicit in-test override only
    client = _FakeClient()
    decision_logger = _logger(tmp_path)
    pending_store = PolymarketPendingOrderStore(tmp_path / "pending.json")
    position_store = PolymarketPositionStore(tmp_path / "positions.json")
    state_store = DailyPnlStateStore(tmp_path / "pnl.json")
    btc_price_store = BtcPriceHistoryStore(tmp_path / "btc.json")
    emergency_stop_store = EmergencyStopStore(tmp_path / "estop.json")
    emergency_stop_store.clear(authorized_by="test", reason="test")
    gateway = LivePolymarketGateway(
        settings, decision_logger, pending_store, order_placer=client, emergency_stop_store=emergency_stop_store,
    )
    return dict(
        client=client, settings=settings, gateway=gateway, position_store=position_store,
        pending_store=pending_store, state_store=state_store, decision_logger=decision_logger,
        btc_price_store=btc_price_store,
    )


def _assess(btc_price_store: BtcPriceHistoryStore, client: _FakeClient, position: OpenPosition, *, now: datetime):
    """Builds the REAL BtcMarketAssessment exactly as
    check_and_execute_dynamic_exits() does internally -- used by tests
    that call evaluate_dynamic_exit() directly (to assert on the
    decision object) rather than only through the full
    check_and_execute_dynamic_exits() orchestrator."""
    bars = btc_price_store.get_bars(interval_seconds=60, now=now)
    order_book = client.get_order_book(position.token_id)
    return bars, order_book, assess_btc_market(bars, order_book, [], outcome=position.outcome, now=now)


# --- 1. INSUFFICIENT_DATA -> HOLD ---------------------------------------------

def test_scenario_1_insufficient_data_holds(tmp_path):
    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    # Only 5 minutes fed -- far below the 35-bar min_bars_for_indicators
    # default, so rsi/macd/ema stay None regardless of price level.
    end_t = _feed(harness["btc_price_store"], [100.0] * 5, seed=1)
    harness["client"].set_order_book("tok-1", _book(0.50))  # would clearly be past target if evaluated

    bars, book, assessment = _assess(harness["btc_price_store"], harness["client"], position, now=end_t + timedelta(seconds=5))
    assert assessment.state == MomentumState.INSUFFICIENT_DATA

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert submitted == 0
    assert harness["position_store"].load()[0].filled_shares == 5.0  # untouched


# --- 2. STRENGTHENING, below target -> HOLD -----------------------------------

def test_scenario_2_strengthening_below_target_holds(tmp_path):
    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _strengthening_closes(), seed=5)
    harness["client"].set_order_book("tok-1", _book(0.378))  # +5%, below the 20% target

    bars, book, assessment = _assess(harness["btc_price_store"], harness["client"], position, now=end_t + timedelta(seconds=5))
    assert assessment.state == MomentumState.STRENGTHENING

    decision = evaluate_dynamic_exit(position, book, assessment, profit_target_pct=0.20)
    assert decision.eligible is False

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert submitted == 0


# --- 3. +20%, STRENGTHENING -> HOLD -------------------------------------------

def test_scenario_3_target_reached_strengthening_holds(tmp_path):
    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _strengthening_closes(), seed=5)
    harness["client"].set_order_book("tok-1", _book(_TARGET_PRICE))

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))

    assert submitted == 0
    positions = harness["position_store"].load()
    assert len(positions) == 1
    assert positions[0].filled_shares == 5.0


# --- 4. +20%, STABLE -> HOLD (v2: reaching the target is context only) -----
# Pre-v2 this scenario documented "target reached + NOT STRENGTHENING ->
# exit" -- the exact rigid P&L/target gate the v2 redesign removed (see
# exit_manager.py's EXPECTED-VALUE REDESIGN module docstring section and
# tests/test_polymarket_dynamic_exit_evidence_model.py's replay scenario
# 6, which covers this identical STABLE/ambiguous-evidence case). Under
# v2 the materiality gate requires WEAKENING/REVERSING specifically;
# STABLE evidence holds regardless of whether the soft target was hit.

def test_scenario_4_target_reached_stable_holds(tmp_path):
    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _STABLE_CLOSES, seed=_STABLE_SEED)
    harness["client"].set_order_book("tok-1", _book(_TARGET_PRICE))

    bars, book, assessment = _assess(harness["btc_price_store"], harness["client"], position, now=end_t + timedelta(seconds=5))
    assert assessment.state == MomentumState.STABLE

    decision = evaluate_dynamic_exit(position, book, assessment, profit_target_pct=0.20)
    assert decision.eligible is False
    assert "p&l is context" in decision.reason.lower()

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert submitted == 0
    assert harness["position_store"].load()[0].filled_shares == 5.0  # untouched -- target reached is not a trigger


# --- 5. +20%, WEAKENING with >=2 signals -> EXIT ------------------------------

def test_scenario_5_target_reached_weakening_with_signals_exits(tmp_path):
    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _WEAKENING_CLOSES, seed=_WEAKENING_SEED)
    harness["client"].set_order_book("tok-1", _book(_TARGET_PRICE))

    bars, book, assessment = _assess(harness["btc_price_store"], harness["client"], position, now=end_t + timedelta(seconds=5))
    assert assessment.state == MomentumState.WEAKENING
    assert len(assessment.btc_assessment.signals) >= 2

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert submitted == 1
    assert harness["position_store"].load() == []


# --- 6. Only +10%, REVERSING with >=2 signals -> EXIT (below target) --------

def test_scenario_6_below_target_strong_reversal_exits(tmp_path):
    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _REVERSING_CLOSES, seed=_REVERSING_SEED)
    ten_pct_bid = round(_AVG_FILL_PRICE * 1.10, 4)
    harness["client"].set_order_book("tok-1", _book(ten_pct_bid))

    bars, book, assessment = _assess(harness["btc_price_store"], harness["client"], position, now=end_t + timedelta(seconds=5))
    assert assessment.state == MomentumState.REVERSING
    assert len(assessment.btc_assessment.signals) >= 2

    decision = evaluate_dynamic_exit(position, book, assessment, profit_target_pct=0.20)
    assert decision.eligible is True
    assert decision.gross_pnl_pct == pytest.approx(0.10, abs=1e-6)  # well below the 20% target

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert submitted == 1
    assert harness["position_store"].load() == []


# --- 7. +35%, STRENGTHENING -> HOLD -------------------------------------------

def test_scenario_7_above_target_strengthening_holds(tmp_path):
    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _strengthening_closes(), seed=5)
    thirty_five_pct_bid = round(_AVG_FILL_PRICE * 1.35, 4)
    harness["client"].set_order_book("tok-1", _book(thirty_five_pct_bid))

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))

    assert submitted == 0
    assert harness["position_store"].load()[0].filled_shares == 5.0


# --- 8. One-tick deterioration -> no premature exit ---------------------------

def test_scenario_8_single_tick_deterioration_does_not_trigger_an_exit(tmp_path):
    """A single bad bar inserted at the very end of an otherwise
    healthy uptrend can at most nudge the state from STRENGTHENING to
    STABLE (never straight to WEAKENING/REVERSING with enough
    signals) -- see evaluate_momentum's own "a single soft signal is
    never enough" guarantee. Evaluated BELOW target so neither the
    early-exit-on-weakening path nor the at-target STABLE-exits path
    can fire; the position must simply hold."""
    base_closes = _strengthening_closes()
    closes_with_one_bad_tick = list(base_closes)
    closes_with_one_bad_tick[-1] = closes_with_one_bad_tick[-2] - 4.0  # one sharp, isolated drop

    harness = _paper_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], closes_with_one_bad_tick, seed=5)
    harness["client"].set_order_book("tok-1", _book(0.378))  # +5%, below target

    bars, book, assessment = _assess(harness["btc_price_store"], harness["client"], position, now=end_t + timedelta(seconds=5))
    # One isolated bad tick never flips STRENGTHENING straight into
    # WEAKENING/REVERSING -- at most a cautious downgrade to STABLE.
    assert assessment.state in (MomentumState.STRENGTHENING, MomentumState.STABLE)

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert submitted == 0
    assert harness["position_store"].load()[0].filled_shares == 5.0


# --- 9. Multiple corroborating signals -> EXIT exactly once -------------------

def test_scenario_9_strong_reversal_exits_exactly_once_across_two_cycles(tmp_path):
    harness = _live_harness(tmp_path, auto_exit_enabled=False)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _REVERSING_CLOSES, seed=_REVERSING_SEED)
    harness["client"].set_order_book("tok-1", _book(_TARGET_PRICE))

    first = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert first == 1
    assert len(harness["pending_store"].load()) == 1
    assert harness["client"].place_order_calls == []  # auto_exit_enabled=False -- stays at awaiting_approval

    # A second cycle, same tick data (nothing new fed), must NOT submit
    # a second exit for the same position -- it only reconciles.
    second = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=10))
    assert second == 0
    assert len(harness["pending_store"].load()) == 1


# --- 10. Partial fill reconciles correctly ------------------------------------

def test_scenario_10_partial_exit_fill_tracks_the_remaining_position(tmp_path):
    harness = _live_harness(tmp_path)
    position = _position(entry_fee_usd=0.05)
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _REVERSING_CLOSES, seed=_REVERSING_SEED)
    harness["client"].set_order_book("tok-1", _book(_TARGET_PRICE))
    harness["client"].set_place_outcome(SubmissionOutcome(ok=True, exchange_order_id="exit-ex-10", raw_status="matched"))
    harness["client"].set_fill_result("exit-ex-10", FillResult(
        order_id="exit-ex-10", status="partially_filled", requested_shares=5.0, filled_shares=3.0,
        avg_fill_price=_TARGET_PRICE, fee_usd=0.018,
    ))

    submitted = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))

    assert submitted == 1
    positions = harness["position_store"].load()
    assert len(positions) == 1
    assert positions[0].filled_shares == pytest.approx(2.0)  # 5 - 3 left open
    assert positions[0].exit_pending_order_id is None  # free to retry next cycle


# --- 11. Unknown exit status -> protected, no duplicate exit -----------------

def test_scenario_11_unknown_exit_status_is_protected_and_not_duplicated(tmp_path):
    harness = _live_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _REVERSING_CLOSES, seed=_REVERSING_SEED)
    harness["client"].set_order_book("tok-1", _book(_TARGET_PRICE))
    harness["client"].set_place_outcome(SubmissionOutcome(ok=True, exchange_order_id="exit-ex-11", raw_status="matched"))
    harness["client"].set_fill_result("exit-ex-11", FillResult(
        order_id="exit-ex-11", status="unknown", requested_shares=5.0, filled_shares=0.0, avg_fill_price=None,
    ))

    first = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert first == 1
    positions = harness["position_store"].load()
    assert positions[0].filled_shares == 5.0
    assert positions[0].exit_pending_order_id is not None  # protected -- never assumed filled

    # A later cycle must re-check the SAME exit, never submit a second one.
    second = check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=10))
    assert second == 0
    assert harness["client"].place_order_calls == [] or len(harness["client"].place_order_calls) == 1


# --- 12. Restart with a pending exit -> reconciliation resumes --------------

def test_scenario_12_restart_with_pending_exit_resumes_correctly(tmp_path):
    harness = _live_harness(tmp_path)
    position = _position()
    harness["position_store"].add_if_absent(position)
    end_t = _feed(harness["btc_price_store"], _REVERSING_CLOSES, seed=_REVERSING_SEED)
    harness["client"].set_order_book("tok-1", _book(_TARGET_PRICE))
    harness["client"].set_place_outcome(SubmissionOutcome(ok=True, exchange_order_id="exit-ex-12", raw_status="matched"))
    harness["client"].set_fill_result("exit-ex-12", FillResult(
        order_id="exit-ex-12", status="unknown", requested_shares=5.0, filled_shares=0.0, avg_fill_price=None,
    ))
    check_and_execute_dynamic_exits(**harness, now=end_t + timedelta(seconds=5))
    assert harness["position_store"].get("client-2230z").exit_pending_order_id is not None

    # Fresh store instances pointed at the same files -- simulates a
    # restarted bot process that lost all in-memory state.
    fresh_position_store = PolymarketPositionStore(tmp_path / "positions.json")
    fresh_pending_store = PolymarketPendingOrderStore(tmp_path / "pending.json")
    fresh_state_store = DailyPnlStateStore(tmp_path / "pnl.json")
    harness["client"].set_fill_result("exit-ex-12", FillResult(
        order_id="exit-ex-12", status="filled", requested_shares=5.0, filled_shares=5.0, avg_fill_price=_TARGET_PRICE,
    ))

    restarted_position = fresh_position_store.get("client-2230z")
    result = reconcile_exit_fill(
        restarted_position, client=harness["client"], pending_store=fresh_pending_store,
        position_store=fresh_position_store, state_store=fresh_state_store, decision_logger=harness["decision_logger"],
    )
    assert result is None  # fully closed
    assert fresh_position_store.load() == []


# --- 13. Resolution before dynamic exit -> settlement fallback handles it ---

def test_scenario_13_settlement_fallback_handles_resolution_before_dynamic_exit(tmp_path):
    """Full run_cycle() integration: dynamic_exit_enabled=true, real
    BTC ticks fed showing no actionable evidence, but the position's
    market has ALREADY closed and resolved -- the UNCHANGED settlement
    path (settle_resolved_positions, called before the dynamic-exit
    check in run_cycle()) must close it via resolution, never via the
    dynamic-exit path."""
    client = _FakeClient()
    client.set_resolution("YES")  # this position's market has resolved, and it won
    settings = _settings(POLYMARKET_DYNAMIC_EXIT_ENABLED="true", POLYMARKET_LOG_DIR=str(tmp_path))
    decision_logger = _logger(tmp_path)
    gateway = PaperPolymarketGateway(settings, decision_logger)
    risk_manager = PolymarketRiskManager(settings)
    strategy = BtcMomentumStrategy()
    position_store = PolymarketPositionStore(tmp_path / "positions.json")
    pending_store = PolymarketPendingOrderStore(tmp_path / "pending.json")
    state_store = DailyPnlStateStore(tmp_path / "pnl.json")
    btc_price_store = BtcPriceHistoryStore(tmp_path / "btc.json")
    history = MarketHistory()

    end_t = _feed(btc_price_store, _STABLE_CLOSES, seed=_STABLE_SEED)  # no actionable BTC evidence either way
    now = end_t + timedelta(seconds=5)
    # Same (fictional, fixed) clock as the fed BTC ticks -- never mixed
    # with real wall-clock time, so "already closed" is unambiguous.
    past_close = now - timedelta(minutes=1)
    position_store.add_if_absent(_position(
        filled_shares=10.0, avg_fill_price=0.5, opened_at=past_close - timedelta(minutes=15), close_time=past_close,
    ))

    report = run_cycle(
        settings=settings, client=client, strategy=strategy, risk_manager=risk_manager, gateway=gateway,
        decision_logger=decision_logger, state_store=state_store, position_store=position_store,
        pending_store=pending_store, history=history, btc_price_store=btc_price_store, now=now,
    )

    assert report.settled_count == 1
    assert report.exits_submitted == 0  # the dynamic-exit path never touched it -- already gone by settlement
    assert position_store.load() == []
    final_state = state_store.load(today=now.date())
    assert final_state.realized_pnl_usd == pytest.approx(5.0)  # 10 shares - $5 cost = $5 profit, exactly as settlement computes


# --- Buffer determinism / no fabrication (btc_market_data.py) ----------------

def test_buffer_produces_deterministic_bars_from_the_same_ticks(tmp_path):
    """Same seed -> same ticks -> byte-identical bars, every run."""
    store_a = BtcPriceHistoryStore(tmp_path / "a.json")
    store_b = BtcPriceHistoryStore(tmp_path / "b.json")
    end_t = _feed(store_a, _WEAKENING_CLOSES, seed=_WEAKENING_SEED)
    _feed(store_b, _WEAKENING_CLOSES, seed=_WEAKENING_SEED)

    bars_a = store_a.get_bars(interval_seconds=60, now=end_t + timedelta(seconds=5))
    bars_b = store_b.get_bars(interval_seconds=60, now=end_t + timedelta(seconds=5))

    assert len(bars_a) == len(bars_b) and len(bars_a) > 0
    for a, b in zip(bars_a, bars_b):
        assert a.open == b.open and a.high == b.high and a.low == b.low and a.close == b.close
        assert a.volume == 0 and b.volume == 0


def test_buffer_never_fabricates_volume_or_vwap(tmp_path):
    """get_crypto_quotes has no volume field -- every BTC-sourced bar's
    volume must be exactly 0 (never guessed), and src/market/indicators
    .vwap() (reused unmodified) must honestly return None for a
    zero-volume series rather than compute a meaningless number."""
    store = BtcPriceHistoryStore(tmp_path / "btc.json")
    end_t = _feed(store, _strengthening_closes(), seed=5)
    bars = store.get_bars(interval_seconds=60, now=end_t + timedelta(seconds=5))
    assert len(bars) > 0
    assert all(bar.volume == 0 for bar in bars)
    assert vwap(bars) is None
