#!/usr/bin/env python3
"""Phase 27, Part 4/5 — fetches EVERY additional real, free,
no-payment historical options file this phase found in
QuantConnect/Lean's repository beyond what Phase 26 already pulled.

Real, confirmed (via WebFetch against github.com/api.github.com/
raw.githubusercontent.com this phase) additions:
  - FOXA, GOOG, NWSA, TWX daily options (quote/trade[/openinterest]) --
    present in Data/option/usa/daily/ but never fetched in Phase 26
    (Phase 26 only pulled AAPL and SPY).
  - GOOG minute options for 3 REAL consecutive trading days
    (2015-12-23, 2015-12-24, 2015-12-28) -- the richest new asset this
    phase found: multi-day minute-resolution real chain data, which
    Phase 26 never had (its only minute sample was a single SPY day).
  - FOXA (2013-07-02), NWSA (2013-06-28), TWX (2014-06-05/06), and
    AAPL (2014-06-06/09) minute options -- all real, all free.
  - FOXA, GOOG, NWSA paired underlying equity daily bars (confirmed
    present in Data/equity/usa/daily/ this phase). TWX has NO paired
    equity file in this repository (confirmed absent) -- its
    underlying-price-dependent certifications (Part 7's IV/Greeks
    reconstruction) will honestly report UNAVAILABLE, never fabricated.

Every file here is REAL_EXTERNAL_DATA (Part 4's required label) --
nothing synthetic is generated by this script. Idempotent: re-running
skips files already present with a matching size, exactly like Phase
26's scripts/phase26_step0_fetch_actual_sample.py (whose own AAPL/SPY
files this script does NOT re-fetch or duplicate).
"""

from __future__ import annotations

import sys
import urllib.request
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "logs/research_data/phase27_raw"
ZIP_DIR = RAW_DIR / "zips"
EXTRACT_DIR = RAW_DIR / "extracted"

BASE_URL = "https://raw.githubusercontent.com/QuantConnect/Lean/master"

# (relative URL path under BASE_URL, local zip filename, extraction subdir, required)
FILES = (
    # --- Daily options, new underlyings (never fetched in Phase 26) ---
    ("Data/option/usa/daily/foxa_2013_quote_american.zip", "foxa_2013_quote_american.zip", "foxa_2013_quote", True),
    ("Data/option/usa/daily/foxa_2013_trade_american.zip", "foxa_2013_trade_american.zip", "foxa_2013_trade", True),
    ("Data/option/usa/daily/goog_2015_openinterest_american.zip", "goog_2015_openinterest_american.zip", "goog_2015_oi", True),
    ("Data/option/usa/daily/goog_2015_quote_american.zip", "goog_2015_quote_american.zip", "goog_2015_quote", True),
    ("Data/option/usa/daily/goog_2015_trade_american.zip", "goog_2015_trade_american.zip", "goog_2015_trade", True),
    ("Data/option/usa/daily/nwsa_2013_quote_american.zip", "nwsa_2013_quote_american.zip", "nwsa_2013_quote", True),
    ("Data/option/usa/daily/nwsa_2013_trade_american.zip", "nwsa_2013_trade_american.zip", "nwsa_2013_trade", True),
    ("Data/option/usa/daily/twx_2014_openinterest_american.zip", "twx_2014_openinterest_american.zip", "twx_2014_oi", True),
    ("Data/option/usa/daily/twx_2014_quote_american.zip", "twx_2014_quote_american.zip", "twx_2014_quote", True),
    ("Data/option/usa/daily/twx_2014_trade_american.zip", "twx_2014_trade_american.zip", "twx_2014_trade", True),
    # --- Minute options: GOOG, 3 real consecutive December 2015 trading days ---
    ("Data/option/usa/minute/goog/20151223_openinterest_american.zip", "goog_20151223_oi.zip", "goog_min_20151223_oi", True),
    ("Data/option/usa/minute/goog/20151223_quote_american.zip", "goog_20151223_quote.zip", "goog_min_20151223_quote", True),
    ("Data/option/usa/minute/goog/20151223_trade_american.zip", "goog_20151223_trade.zip", "goog_min_20151223_trade", True),
    ("Data/option/usa/minute/goog/20151224_openinterest_american.zip", "goog_20151224_oi.zip", "goog_min_20151224_oi", True),
    ("Data/option/usa/minute/goog/20151224_quote_american.zip", "goog_20151224_quote.zip", "goog_min_20151224_quote", True),
    ("Data/option/usa/minute/goog/20151224_trade_american.zip", "goog_20151224_trade.zip", "goog_min_20151224_trade", True),
    ("Data/option/usa/minute/goog/20151228_quote_american.zip", "goog_20151228_quote.zip", "goog_min_20151228_quote", True),
    ("Data/option/usa/minute/goog/20151228_trade_american.zip", "goog_20151228_trade.zip", "goog_min_20151228_trade", True),
    # --- Minute options: other real single/double days ---
    ("Data/option/usa/minute/foxa/20130702_quote_american.zip", "foxa_20130702_quote.zip", "foxa_min_20130702_quote", True),
    ("Data/option/usa/minute/foxa/20130702_trade_american.zip", "foxa_20130702_trade.zip", "foxa_min_20130702_trade", True),
    ("Data/option/usa/minute/nwsa/20130628_quote_american.zip", "nwsa_20130628_quote.zip", "nwsa_min_20130628_quote", True),
    ("Data/option/usa/minute/nwsa/20130628_trade_american.zip", "nwsa_20130628_trade.zip", "nwsa_min_20130628_trade", True),
    ("Data/option/usa/minute/twx/20140605_openinterest_american.zip", "twx_20140605_oi.zip", "twx_min_20140605_oi", True),
    ("Data/option/usa/minute/twx/20140605_quote_american.zip", "twx_20140605_quote.zip", "twx_min_20140605_quote", True),
    ("Data/option/usa/minute/twx/20140605_trade_american.zip", "twx_20140605_trade.zip", "twx_min_20140605_trade", True),
    ("Data/option/usa/minute/twx/20140606_openinterest_american.zip", "twx_20140606_oi.zip", "twx_min_20140606_oi", True),
    ("Data/option/usa/minute/twx/20140606_quote_american.zip", "twx_20140606_quote.zip", "twx_min_20140606_quote", True),
    ("Data/option/usa/minute/twx/20140606_trade_american.zip", "twx_20140606_trade.zip", "twx_min_20140606_trade", True),
    ("Data/option/usa/minute/aapl/20140606_openinterest_american.zip", "aapl_min_20140606_oi.zip", "aapl_min_20140606_oi", True),
    ("Data/option/usa/minute/aapl/20140606_quote_american.zip", "aapl_min_20140606_quote.zip", "aapl_min_20140606_quote", True),
    ("Data/option/usa/minute/aapl/20140606_trade_american.zip", "aapl_min_20140606_trade.zip", "aapl_min_20140606_trade", True),
    ("Data/option/usa/minute/aapl/20140609_openinterest_american.zip", "aapl_min_20140609_oi.zip", "aapl_min_20140609_oi", True),
    ("Data/option/usa/minute/aapl/20140609_quote_american.zip", "aapl_min_20140609_quote.zip", "aapl_min_20140609_quote", True),
    ("Data/option/usa/minute/aapl/20140609_trade_american.zip", "aapl_min_20140609_trade.zip", "aapl_min_20140609_trade", True),
    # --- Paired underlying equity daily bars (confirmed present this phase) ---
    ("Data/equity/usa/daily/foxa.zip", "foxa_equity_daily.zip", "foxa_equity", True),
    ("Data/equity/usa/daily/goog.zip", "goog_equity_daily.zip", "goog_equity", True),
    ("Data/equity/usa/daily/nwsa.zip", "nwsa_equity_daily.zip", "nwsa_equity", True),
    # TWX equity: confirmed ABSENT from this repository's real listing this phase --
    # deliberately NOT attempted (would only ever fail); reported as UNAVAILABLE,
    # not silently skipped without explanation.
)


def fetch(url_path: str, dest: Path) -> None:
    url = f"{BASE_URL}/{url_path}"
    req = urllib.request.Request(url, headers={"User-Agent": "hood-research-phase27/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:  # noqa: S310 -- fixed https, github raw content only
        data = resp.read()
    dest.write_bytes(data)


def main() -> None:
    ZIP_DIR.mkdir(parents=True, exist_ok=True)
    EXTRACT_DIR.mkdir(parents=True, exist_ok=True)

    failures = []
    for url_path, filename, extract_subdir, required in FILES:
        dest = ZIP_DIR / filename
        if dest.is_file() and dest.stat().st_size > 0:
            print(f"SKIP (already present, {dest.stat().st_size} bytes): {filename}", flush=True)
        else:
            print(f"FETCH: {url_path}", flush=True)
            try:
                fetch(url_path, dest)
            except Exception as exc:  # noqa: BLE001 -- report and continue; never fabricate a substitute
                print(f"FAILED to fetch {url_path}: {exc}", file=sys.stderr, flush=True)
                failures.append(url_path)
                continue
            print(f"  -> {dest.stat().st_size} bytes", flush=True)

        out_dir = EXTRACT_DIR / extract_subdir
        if out_dir.is_dir() and any(out_dir.iterdir()):
            print(f"  (already extracted to {out_dir})", flush=True)
        else:
            out_dir.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(dest) as zf:
                zf.extractall(out_dir)
            print(f"  extracted -> {out_dir} ({len(list(out_dir.iterdir()))} files)", flush=True)

    print(f"\nSTEP 0 COMPLETE — {len(FILES) - len(failures)}/{len(FILES)} real files fetched. "
          f"Failures (if any, NOT fabricated as substitutes): {failures or 'none'}", flush=True)
    print(f"Raw files under {RAW_DIR}", flush=True)
    if failures:
        sys.exit(1)


if __name__ == "__main__":
    main()
